String params = "["
  "{"
  "'name':'ssid',"
  "'label':'Name of WLAN',"
  "'type':"+String(INPUTTEXT)+","
  "'default':''"
  "},"
  "{"
  "'name':'pwd',"
  "'label':'WLAN Password',"
  "'type':"+String(INPUTPASSWORD)+","
  "'default':''"
  "},"
  "{"
  "'name':'mqtt-address',"
  "'label':'MQTT IP ADDRESS',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'192.168.1.179'"
  "},"
  "{"
  "'name':'mqtt-username',"
  "'label':'MQTT User Name',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'esp'"
  "}," 
  "{"
  "'name':'mqtt-pw',"
  "'label':'MQTT Password',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'password'"
  "},"
  "{"
  "'name':'mqtt-topic',"
  "'label':'MQTT Topic',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'Logix_Base'"
  "}," 
  "{"
  "'name':'mqtt-port',"
  "'label':'MQTT Port',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'1883'"
  "}," 
  "{"
  "'name':'mqtt-ad',"
  "'label':'MQTT Auto Discovery',"
  "'type':"+String(INPUTCHECKBOX)+","
  "'default':'0'"
  "},"
  "{"
  "'name':'button-1',"
  "'label':'Button Name',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'vent_button'"
  "},"
  "{"
  "'name':'vent-1',"
  "'label':'Vent Name',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'vent'"
  "}"
  "]";
